<a href="https://colab.research.google.com/github/Manu-Gr/Recommendation-System---Assignment---Books/blob/main/Recommendation_System_Assignment_Books.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###**Recommendation System - Assignment - Books**

#### **Import the Libraries**

In [ ]:
import pandas as pd
import numpy as np

#### **Import the dataset**

In [ ]:
book = pd.read_csv('book1.csv')
book

Unnamed: 0  ...  Book.Rating
0              1  ...            5
1              2  ...            3
2              3  ...            6
3              4  ...            8
4              5  ...            6
...          ...  ...          ...
9995        9996  ...            7
9996        9997  ...            9
9997        9998  ...            7
9998        9999  ...            8
9999       10000  ...            6

[10000 rows x 4 columns]

In [ ]:
book.shape

(10000, 4)

In [ ]:
book1 = book.iloc[:,1:]
book1

User.ID                                         Book.Title  Book.Rating
0      276726                                Classical Mythology            5
1      276729                                       Clara Callan            3
2      276729                               Decision in Normandy            6
3      276736  Flu: The Story of the Great Influenza Pandemic...            8
4      276737                             The Mummies of Urumchi            6
...       ...                                                ...          ...
9995   162121       American Fried: Adventures of a Happy Eater.            7
9996   162121                              Cannibal In Manhattan            9
9997   162121                    How to Flirt: A Practical Guide            7
9998   162121                                           Twilight            8
9999   162129                       Kids Say the Darndest Things            6

[10000 rows x 3 columns]

In [ ]:
book1['User.ID'].nunique()

2182

In [ ]:
book1['Book.Title'].nunique()

9659

####**User Based Colloborative filtering**

#### **Colloborative filtering using Correlation Matrix**

In [ ]:
cor_piv_table =pd.pivot_table(data = book1, values = 'Book.Rating', index ='Book.Title',columns = 'User.ID').fillna(0)
cor_piv_table

User.ID                                             8       ...  278854
Book.Title                                                  ...        
 Jason, Madison &amp                                   0.0  ...     0.0
 Other Stories;Merril;1985;McClelland &amp             0.0  ...     0.0
 Repairing PC Drives &amp                              0.0  ...     0.0
'48                                                    0.0  ...     0.0
'O Au No Keia: Voices from Hawai'I's Mahu and T...     0.0  ...     0.0
...                                                    ...  ...     ...
\Surely You're Joking, Mr. Feynman!\: Adventure...     0.0  ...     0.0
\Well, there's your problem\: Cartoons                 0.0  ...     0.0
iI Paradiso Degli Orchi                                0.0  ...     0.0
stardust                                               0.0  ...     0.0
Ã?Â?bermorgen.                                         0.0  ...     0.0

[9659 rows x 2182 columns]

In [ ]:
# Replacing index values with unique user ID
cor_piv_table.columns = book1['User.ID'].unique()

In [ ]:
cor_piv_table

276726  ...  162129
Book.Title                                                  ...        
 Jason, Madison &amp                                   0.0  ...     0.0
 Other Stories;Merril;1985;McClelland &amp             0.0  ...     0.0
 Repairing PC Drives &amp                              0.0  ...     0.0
'48                                                    0.0  ...     0.0
'O Au No Keia: Voices from Hawai'I's Mahu and T...     0.0  ...     0.0
...                                                    ...  ...     ...
\Surely You're Joking, Mr. Feynman!\: Adventure...     0.0  ...     0.0
\Well, there's your problem\: Cartoons                 0.0  ...     0.0
iI Paradiso Degli Orchi                                0.0  ...     0.0
stardust                                               0.0  ...     0.0
Ã?Â?bermorgen.                                         0.0  ...     0.0

[9659 rows x 2182 columns]

In [ ]:
cor_piv_table.corr()

276726    276729    276736  ...    162113    162121    162129
276726  1.000000 -0.000272 -0.000272  ... -0.000991 -0.000272 -0.000663
276729 -0.000272  1.000000 -0.000104  ... -0.000378 -0.000104 -0.000253
276736 -0.000272 -0.000104  1.000000  ... -0.000378 -0.000104 -0.000253
276737 -0.000272 -0.000104 -0.000104  ... -0.000378 -0.000104 -0.000253
276744 -0.000469 -0.000179 -0.000179  ... -0.000652 -0.000179 -0.000436
...          ...       ...       ...  ...       ...       ...       ...
162107 -0.000272 -0.000104 -0.000104  ... -0.000378 -0.000104 -0.000253
162109 -0.000272 -0.000104 -0.000104  ... -0.000378 -0.000104 -0.000253
162113 -0.000991 -0.000378 -0.000378  ...  1.000000 -0.000378 -0.000922
162121 -0.000272 -0.000104 -0.000104  ... -0.000378  1.000000 -0.000253
162129 -0.000663 -0.000253 -0.000253  ... -0.000922 -0.000253  1.000000

[2182 rows x 2182 columns]

In [ ]:
cor1 = cor_piv_table.corr()

In [ ]:
# fill diagonal with 0
cor2 = cor1.values
cor2

array([[ 1.00000000e+00, -2.71714970e-04, -2.71714970e-04, ...,
        -9.91259776e-04, -2.71714970e-04, -6.63481070e-04],
       [-2.71714970e-04,  1.00000000e+00, -1.03541106e-04, ...,
        -3.77734555e-04, -1.03541106e-04, -2.52829514e-04],
       [-2.71714970e-04, -1.03541106e-04,  1.00000000e+00, ...,
        -3.77734555e-04, -1.03541106e-04, -2.52829514e-04],
       ...,
       [-9.91259776e-04, -3.77734555e-04, -3.77734555e-04, ...,
         1.00000000e+00, -3.77734555e-04, -9.22362604e-04],
       [-2.71714970e-04, -1.03541106e-04, -1.03541106e-04, ...,
        -3.77734555e-04,  1.00000000e+00, -2.52829514e-04],
       [-6.63481070e-04, -2.52829514e-04, -2.52829514e-04, ...,
        -9.22362604e-04, -2.52829514e-04,  1.00000000e+00]])

#### **Colloborative filtering using Euclidean Matrix**

In [ ]:
from sklearn.metrics import pairwise_distances

In [ ]:
Euclidean_piv_table =pd.pivot_table(data = book1, values = 'Book.Rating', index ='User.ID',columns = 'Book.Title').fillna(0)
Euclidean_piv_table

Book.Title   Jason, Madison &amp  ...  Ã?Â?bermorgen.
User.ID                           ...                
8                            0.0  ...             0.0
9                            0.0  ...             0.0
10                           0.0  ...             0.0
12                           0.0  ...             0.0
14                           0.0  ...             0.0
...                          ...  ...             ...
278846                       0.0  ...             0.0
278849                       0.0  ...             0.0
278851                       0.0  ...             0.0
278852                       0.0  ...             0.0
278854                       0.0  ...             0.0

[2182 rows x 9659 columns]

In [ ]:
Euclidean_piv_table.index = book1['User.ID'].unique()


In [ ]:
Euclidean_piv_table

Book.Title   Jason, Madison &amp  ...  Ã?Â?bermorgen.
276726                       0.0  ...             0.0
276729                       0.0  ...             0.0
276736                       0.0  ...             0.0
276737                       0.0  ...             0.0
276744                       0.0  ...             0.0
...                          ...  ...             ...
162107                       0.0  ...             0.0
162109                       0.0  ...             0.0
162113                       0.0  ...             0.0
162121                       0.0  ...             0.0
162129                       0.0  ...             0.0

[2182 rows x 9659 columns]

In [ ]:
Euclidean_piv_table.values

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 7., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
Euc1 = pairwise_distances(X = Euclidean_piv_table.values, metric='euclidean')
Euc1

array([[ 0.        , 16.03121954, 16.03121954, ..., 29.05167809,
        16.88194302, 22.737634  ],
       [16.03121954,  0.        ,  8.48528137, ..., 25.67099531,
        10.        , 18.22086716],
       [16.03121954,  8.48528137,  0.        , ..., 25.67099531,
        10.        , 18.22086716],
       ...,
       [29.05167809, 25.67099531, 25.67099531, ...,  0.        ,
        26.21068484, 30.31501278],
       [16.88194302, 10.        , 10.        , ..., 26.21068484,
         0.        , 18.97366596],
       [22.737634  , 18.22086716, 18.22086716, ..., 30.31501278,
        18.97366596,  0.        ]])

In [ ]:
Euc2          = pd.DataFrame(data= Euc1)
Euc2.index    = book1['User.ID'].unique()
Euc2.columns  = book1['User.ID'].unique()
Euc2.round(2)

276726  276729  276736  276737  ...  162109  162113  162121  162129
276726    0.00   16.03   16.03   17.92  ...   17.38   29.05   16.88   22.74
276729   16.03    0.00    8.49   11.66  ...   10.82   25.67   10.00   18.22
276736   16.03    8.49    0.00   11.66  ...   10.82   25.67   10.00   18.22
276737   17.92   11.66   11.66    0.00  ...   13.45   26.89   12.81   19.90
276744   17.52   11.05   11.05   13.64  ...   12.92   26.63   12.25   19.54
...        ...     ...     ...     ...  ...     ...     ...     ...     ...
162107   16.88   10.00   10.00   12.81  ...   12.04   26.21   11.31   18.97
162109   17.38   10.82   10.82   13.45  ...    0.00   26.53   12.04   19.42
162113   29.05   25.67   25.67   26.89  ...   26.53    0.00   26.21   30.32
162121   16.88   10.00   10.00   12.81  ...   12.04   26.21    0.00   18.97
162129   22.74   18.22   18.22   19.90  ...   19.42   30.32   18.97    0.00

[2182 rows x 2182 columns]

#### **Colloborative filtering using Cosine Matrix**

In [ ]:
Cosine_piv_table =pd.pivot_table(data = book1, values = 'Book.Rating', index ='User.ID',columns = 'Book.Title').fillna(0)
Cosine_piv_table

Book.Title   Jason, Madison &amp  ...  Ã?Â?bermorgen.
User.ID                           ...                
8                            0.0  ...             0.0
9                            0.0  ...             0.0
10                           0.0  ...             0.0
12                           0.0  ...             0.0
14                           0.0  ...             0.0
...                          ...  ...             ...
278846                       0.0  ...             0.0
278849                       0.0  ...             0.0
278851                       0.0  ...             0.0
278852                       0.0  ...             0.0
278854                       0.0  ...             0.0

[2182 rows x 9659 columns]

In [ ]:
Cosine_piv_table.index = book1['User.ID'].unique()

In [ ]:
Cosine_piv_table

Book.Title   Jason, Madison &amp  ...  Ã?Â?bermorgen.
276726                       0.0  ...             0.0
276729                       0.0  ...             0.0
276736                       0.0  ...             0.0
276737                       0.0  ...             0.0
276744                       0.0  ...             0.0
...                          ...  ...             ...
162107                       0.0  ...             0.0
162109                       0.0  ...             0.0
162113                       0.0  ...             0.0
162121                       0.0  ...             0.0
162129                       0.0  ...             0.0

[2182 rows x 9659 columns]

In [ ]:
Cosine_piv_table.values

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 7., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
Cosine_ubcf =  1 - pairwise_distances(X = Cosine_piv_table.values, metric='cosine')
Cosine_ubcf

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [ ]:
Cosine = pd.DataFrame(data= Cosine_ubcf)
Cosine.index    = book1['User.ID'].unique()
Cosine.columns  = book1['User.ID'].unique()
Cosine

276726  276729  276736  276737  ...  162109  162113  162121  162129
276726     1.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
276729     0.0     1.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
276736     0.0     0.0     1.0     0.0  ...     0.0     0.0     0.0     0.0
276737     0.0     0.0     0.0     1.0  ...     0.0     0.0     0.0     0.0
276744     0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
...        ...     ...     ...     ...  ...     ...     ...     ...     ...
162107     0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
162109     0.0     0.0     0.0     0.0  ...     1.0     0.0     0.0     0.0
162113     0.0     0.0     0.0     0.0  ...     0.0     1.0     0.0     0.0
162121     0.0     0.0     0.0     0.0  ...     0.0     0.0     1.0     0.0
162129     0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     1.0

[2182 rows x 2182 columns]

In [ ]:
first_100_users = Cosine.iloc[:100,:100]
first_100_users

276726  276729  276736  276737  ...  277042  277048  277051  277052
276726     0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
276729     0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
276736     0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
276737     0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
276744     0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
...        ...     ...     ...     ...  ...     ...     ...     ...     ...
277036     0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
277042     0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
277048     0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
277051     0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
277052     0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0

[100 rows x 100 columns]

In [ ]:
# fill diagonal with 0
first_100_users = np.fill_diagonal(a = first_100_users.to_numpy(),val = 0)
first_100_users

In [ ]:
first_100_users.idxmax(axis=1)

276726    276726
276729    276726
276736    276726
276737    276726
276744    276726
           ...  
277036    276726
277042    276726
277048    276726
277051    276726
277052    276726
Length: 100, dtype: int64

In [ ]:
Cosine1 = Cosine
Cosine1

276726  276729  276736  276737  ...  162109  162113  162121  162129
276726     0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
276729     0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
276736     0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
276737     0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
276744     0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
...        ...     ...     ...     ...  ...     ...     ...     ...     ...
162107     0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
162109     0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
162113     0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
162121     0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
162129     0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0

[2182 rows x 2182 columns]

In [ ]:
Cosine

276726  276729  276736  276737  ...  162109  162113  162121  162129
276726     0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
276729     0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
276736     0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
276737     0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
276744     0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
...        ...     ...     ...     ...  ...     ...     ...     ...     ...
162107     0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
162109     0.0     0.0     0.0     0.0  ...     1.0     0.0     0.0     0.0
162113     0.0     0.0     0.0     0.0  ...     0.0     1.0     0.0     0.0
162121     0.0     0.0     0.0     0.0  ...     0.0     0.0     1.0     0.0
162129     0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     1.0

[2182 rows x 2182 columns]

In [ ]:
# Most Similar Users
Cosine1.idxmax()

276726    276726
276729    276726
276736    276726
276737    276726
276744    276726
           ...  
162107    276726
162109    276726
162113    161453
162121    276726
162129    276726
Length: 2182, dtype: int64

In [ ]:
# extract the books which userId 276726 & 276729 have watched
book1[(book1['User.ID']==276726) | (book1['User.ID']==276729)]

User.ID            Book.Title  Book.Rating
0   276726   Classical Mythology            5
1   276729          Clara Callan            3
2   276729  Decision in Normandy            6

In [ ]:
# extract the books which userId 162107 & 276726 have watched
book1[(book1['User.ID']==162107) | (book1['User.ID']==276726)]

User.ID               Book.Title  Book.Rating
0      276726      Classical Mythology            5
9987   162107  What's Bred in the Bone            7

In [ ]:
# extract the books which userId 162109 & 276726 have watched
book1[(book1['User.ID']==162109) | (book1['User.ID']==276726)]

User.ID               Book.Title  Book.Rating
0      276726      Classical Mythology            5
9988   162109  The Flower in the Skull           10

In [ ]:
# extract the books which userId 276737 & 276726 have watched
book1[(book1['User.ID']==276737) | (book1['User.ID']==276726)]

User.ID              Book.Title  Book.Rating
0   276726     Classical Mythology            5
4   276737  The Mummies of Urumchi            6

In [ ]:
# extract the books which userId 276737 & 276726 have watched
book1[(book1['User.ID']==277958) | (book1['User.ID']==276726)]

User.ID           Book.Title  Book.Rating
0      276726  Classical Mythology            5
1351   277958       Darwin's Radio            9